# Generated by Django 5.2.9 on 2025-12-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial_nomi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '1. Asosiy Audit',
                'verbose_name_plural': '1. Asosiy Auditlar',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.category')),
            ],
        ),
        migrations.CreateModel(
            name='AuditDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.CharField(max_length=10, verbose_name='Band IDsi (Savol)')),
                ('score', models.IntegerField(verbose_name='Kiritilgan Ball (0-3)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='audit_images/', verbose_name='Rasm')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='checklist.audit', verbose_name='Audit')),
            ],
            options={
                'verbose_name': '2. Audit Detali (Savollar)',
                'verbose_name_plural': '2. Audit Detallari',
                'unique_together': {('audit', 'band_id')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.item')),
            ],
            options={
                'unique_together': {('branch', 'item')},
            },
        ),
    ]
