# Generated by Django 5.2.9 on 2025-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='total_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
