# Generated by Django 5.2.9 on 2025-12-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_audit_total_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={},
        ),
    ]
