# Generated by Django 5.2.9 on 2025-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_audit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Vaqti'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='filial_nomi',
            field=models.CharField(max_length=255, verbose_name='Filial Nomi'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='total_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Umumiy Foiz'),
        ),
    ]
