# Generated by Django 5.2.9 on 2025-12-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_branch_is_active_branch_pin_branch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='auditor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
