# Generated by Django 5.2.9 on 2025-12-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_audit_auditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdetail',
            name='band_id',
            field=models.CharField(max_length=255, verbose_name='Band IDsi (Savol)'),
        ),
    ]
