# Generated by Django 5.2.9 on 2026-01-09 05:30

import checklist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_alter_auditdetail_band_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=checklist.models.audit_image_path),
        ),
    ]
